name: Continuous Integration

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup:
    name: Generate build matrix
    runs-on: ubuntu-latest

    outputs:
      minor: ${{ steps.releases.outputs.minor }}

    steps:
      - id: releases
        name: Get PHP Releases
        uses: flavioheleno/php-active-releases-action@67d68847bcb86a24f235f2eef9536aac16a9374d # v0.2.1

  build:
    name: Build matrix
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJson(needs.setup.outputs.minor) }}
        type:
          - nts
          - ts

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@fc14643b0a99ee9db10a3c025a33d76544fa3761 # v2.30.5
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: none
          tools: phpize, php-config
        env:
          phpts: ${{ matrix.type }}
          update: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libmicrohttpd-dev -y

      - name: Build otter
        run: make build

      - name: Run test suite
        run: make test
        env:
          NO_INTERACTION: 1
          REPORT_EXIT_STATUS: 1
